### Documentation

#### Annotation resources

The analysis performed in the _oncoEnrichR report_ is based on the following tools and knowledge resources:

* __Software__ 
```{r list_software, echo=F,results='asis'}
for(n in names(onc_enrich_report[['config']][['resources']])){
  if(onc_enrich_report[['config']][['resources']][[n]]$resource_type == 'software'){
    s <- paste0('    * [',onc_enrich_report[['config']][['resources']][[n]]$name,'](',onc_enrich_report[['config']][['resources']][[n]]$url,') - ',onc_enrich_report[['config']][['resources']][[n]]$description, ' (',onc_enrich_report[['config']][['resources']][[n]]$version,')')
    cat(s,sep="\n")
  }
}

```
<br><br>

* __Databases/datasets__ 
```{r list_db, echo=F,results='asis'}
for(n in names(onc_enrich_report[['config']][['resources']])){
  if(onc_enrich_report[['config']][['resources']][[n]]$resource_type != 'software'){
      s <- paste0('    * [',onc_enrich_report[['config']][['resources']][[n]]$name,'](',onc_enrich_report[['config']][['resources']][[n]]$url,') - ',onc_enrich_report[['config']][['resources']][[n]]$description, ' (',onc_enrich_report[['config']][['resources']][[n]]$version,')')
      cat(s,sep="\n")
  }
}

```
