### Drug-target associations

* Each protein in the target set is annotated with:
   * Targeted cancer drugs (inhibitors/antagonists), as found through the [Open Targets Platform](https://targetvalidation.org)
   * We distinguish between drugs in <i>early clinical development/phase (<b>ep</b>)</i>, and drugs already in <i>late clinical development/phase (<b>lp</b>)</i>

<br><br>


```{r filter_drug_targets, echo=F, results='asis'}

show_drug_targets <- FALSE
missing_drug_targets <- TRUE

if(nrow(onc_enrich_report[['data']][['drug']][['target']]$target) > 0){
  show_drug_targets <- TRUE
  missing_drug_targets <- FALSE
}

```



```{r table_browse_drug_targets, echo=F, results = "asis", eval = show_drug_targets}
library(crosstalk)

targets_shared <- onc_enrich_report[['data']][['drug']][['target']]$target


htmltools::br()
  DT::datatable(targets_shared, escape = F, extensions=c("Buttons","Responsive"), width = "100%",
    options=list(buttons = c('csv','excel'),dom = 'Bfrtip'))



```


```{r drug_targets_missing, echo=F, results = 'asis', eval = missing_drug_targets}
cat('<i>No target proteins with cancer drug associations from Open Targets Platform were found.</i>',sep='\n')
cat('\n')
```


<br><br>
