---
title: "OncoEnrichR report - `r onc_enrich_report[['config']][['project_title']]`"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
bibliography: '`r system.file("bibliography.bib", package = "oncoEnrichR")`'
nocite: |
  @Kanehisa2000-nm, @Joshi-Tope2005-bw, @Kelder2012-vj, @Ashburner2000-sy, @Von_Mering2005-jy, @Petryszak2016-jp, @Giurgiu2019-yu, @Koscielny2017-ay, @Yu2012-yk, @Clauset2004-ov, @Kleinberg1999-oo, @Hart2016-ic, @Iorio2018-ph, @Subramanian2005-ci, @Uhlen2015-sh, @Uhlen2017-mg, @Jain2019-eh, @Lever2019-xn, @Mermel2011-bp, @Kandasamy2010-te, @Behan2019-tf, @Hanahan2011-da, @Turei2016-wq, @Drew2021-kd, @Garcia-Alonso2019-mr, @Jin2021-tf, @De_Kegel2021-xo, @Smith2022-mk
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = F,warning=FALSE, dpi=72, error=F, eval=T)
```

<br>
```{r project_background, child='_project_background.Rmd', eval = T}
```

```{r project_background, child='_query_verification.Rmd', eval = T}
```

```{r target_disease, child='_cancer_association.Rmd', eval = onc_enrich_report[['config']][['show']][['disease']]}
```

```{r target_hallmark, child='_cancer_hallmark_association.Rmd', eval = onc_enrich_report[['config']][['show']][['cancer_hallmark']]}
```

```{r target_unknown, child='_unknown_function.Rmd', eval = onc_enrich_report[['config']][['show']][['unknown_function']]}
```

```{r target_drug, child='_drug_target_association.Rmd', eval = onc_enrich_report[['config']][['show']][['drug']]}
```


```{r target_synthetic_lethality, child='_synthetic_lethality.Rmd', eval = onc_enrich_report[['config']][['show']][['synleth']]}
```


```{r target_fitness, child='_fitness_lof.Rmd', eval = onc_enrich_report[['config']][['show']][['fitness']]}
```

```{r target_complex, child='_protein_complex.Rmd', eval = onc_enrich_report[['config']][['show']][['protein_complex']]}
```

```{r target_domain, child='_protein_domain.Rmd', eval = onc_enrich_report[['config']][['show']][['protein_domain']]}
```


```{r target_ppi, child='_ppi.Rmd', eval = onc_enrich_report[['config']][['show']][['ppi']]}
```

```{r target_ligand_receptor, child='_ligand_receptor.Rmd', eval = onc_enrich_report[['config']][['show']][['ligand_receptor']]}
```


```{r target_regulatory, child='_regulatory_interactions.Rmd', eval = onc_enrich_report[['config']][['show']][['regulatory']]}
```

```{r target_subcell, child='_subcell_comp.Rmd', eval = onc_enrich_report[['config']][['show']][['subcellcomp']]}
```

```{r target_enrichment_invalid, child='_functional_enrichment_invalid.Rmd', eval = NROW(onc_enrich_report[['data']][['query']][['target']] %>% dplyr::filter(status == "found")) < 5}
```

```{r target_enrichment, child='_functional_enrichment.Rmd', eval = onc_enrich_report[['config']][['show']][['enrichment']]}
```

```{r target_cell_tissue, child='_cell_tissue.Rmd', eval = onc_enrich_report[['config']][['show']][['cell_tissue']]}
```

```{r target_tcga_aberration, child='_aberration.Rmd', eval = onc_enrich_report[['config']][['show']][['aberration']]}
```

```{r target_tcga_coexpression, child='_coexpression.Rmd', eval = onc_enrich_report[['config']][['show']][['coexpression']]}
```

```{r target_cancer_prognosis, child='_prognosis_survival.Rmd', eval = onc_enrich_report[['config']][['show']][['cancer_prognosis']]}
```


```{r documentation_workflow, child='_documentation_workflow.Rmd', eval = onc_enrich_report[['data']][['query']]$validation_status != "imperfect_stop"}
```

<br><br>

### References

