### Protein-protein interaction network

* The target set is queried against known protein-protein interactions, as evident from the [STRING database (v11)](http://string-db.org)
  * Note that interactions in STRING are assembled from multiple sources, including co-expression, co-occurrence in the literature, experimental data, curated databases etc
  * In addition to potential interactions within the target set, the network is expanded with __n = `r onc_enrich_report[['config']][['ppi']][['stringdb']][['add_nodes']]`__ proteins that interact with proteins in the target set
  * Network is here restricted to interactions with __STRING association score >= `r onc_enrich_report[['config']][['ppi']][['stringdb']][['minimum_score']]`__ (range 0-1000))

<br>

* Network legend:
  * Target set proteins are **circles**, other interacting proteins are **rectangles** (note that sizes of nodes do not carry any value)
  * Tumor suppressor genes (annotated from [CancerMine](https://www.nature.com/articles/s41592-019-0422-y)) are highlighted in <span style="color:firebrick"><b>red</b></span>
  * Proto-oncogenes (annotated from [CancerMine](https://www.nature.com/articles/s41592-019-0422-y)) are highligted in <span style="color:darkolivegreen"><b>green</b></span>
  * Genes predicted to have a dual role as proto-oncogenes/tumor suppressors (annotated from [CancerMine](https://www.nature.com/articles/s41592-019-0422-y)) are highligted in <span style="color:black"><b>black</b></span>
  

<br><br>
```{r ppi_high, echo = F, results = "asis", eval = T, fig.width = 12, fig.height=13}
visNetwork::visNetwork(onc_enrich_report[['data']][['ppi']][['stringdb']][['network']]$nodes, 
                       onc_enrich_report[['data']][['ppi']][['stringdb']][['network']]$edges) %>%
  visNetwork::visPhysics(stabilization = FALSE) %>%
  visNetwork::visEdges(smooth = FALSE)

```
<br><br>
